version: 2
jobs:
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Test
          command: bin/check
      - store_artifacts:
          path: coverage
          prefix: coverage
  deploy:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Deploy
          command: yarn gh-publish
workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - deploy:
          # requires:
          #   - test
          filters:
            branches:
              only: master
